version: '1.0.1'
services:
  web_admin_revit:
    image: voixmomotalk/web_admin_revit:1.0.1
    ports:
      - 80:80
  api_revit:
    image: voixmomotalk/api_revit:1.0.1
    ports:
      - 8080:80
  sql_server:
    image: voixmomotalk/database_revit:1.0.2
    ports:
      - 1433:1433
    volumes:
      - my-volume:/var/opt/mssql
volumes:
  my-volume:
